image: raatiniemi/gradle:latest

stages:
  - test
  - build

test:
  stage: test
  script:
    - ./bin/test
  tags:
    - docker

build:
  stage: build
  script:
    - ./bin/build
  tags:
    - docker
