image: gradle:4.10.1-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  key: "$CI_COMMIT_REF_NAME"
  policy: push
  paths:
  - .gradle
  - build

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test

build:
  stage: build
  script:
    - gradle clean --build-cache build
  artifacts:
    paths:
      - build
    expire_in: 1 day
  tags:
    - docker

test:
  stage: test
  script:
    - gradle test
  except:
    - master
  tags:
    - docker

analyse:
  stage: test
  script:
    - gradle sonarqube
  only:
    - master
  tags:
    - docker
